Repository nicmart/Tree, pull requests merged in 2020-11, with the labels that each got.

#79 Support for PHP 8.0
  .github/workflows/integrate.yaml
  CHANGELOG.md
  composer.json
  composer.lock
Labels: enhancement

#82 Fix: Reference
  CHANGELOG.md
Labels: bug, merge

#83 Fix: Simplify installation instructions
  README.md
Labels: bug
